on:
  push:
    branches:
    - main

name: main
jobs:

  linux:
    name: 'Linux'
    container:
      image: mcr.microsoft.com/dotnet/sdk:latest
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build and Test
      run: |
        dotnet build
        dotnet test
